backend:
  name: git-gateway
  repo: mbernardes19/o-portal-do-empreendedor.git
  branch: main
media_folder: public/images/uploads
local_backend:
  url: http://localhost:8081/api/v1
  allowed_hosts: ['127.0.0.1']
collections:
  - name: "footer-section"
    label: "Footer Section"
    folder: "content/footer-section"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: json
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Links",
          name: "links",
          widget: "list",
          summary: "{{fields.url}}",
          allow_add: true,
          field:
            {
              label: Link,
              name: link,
              widget: object,
              summary: "{{fields.name}}",
              fields: [
                {
                  label: Name,
                  name: name,
                  widget: string
                },
                {
                  label: URL,
                  name: url,
                  widget: string
                }
              ]
            }
        }
  - name: "footer"
    label: "Footer"
    folder: "content/footer"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: json
    fields:
      - {label: "Copyright text", name: "copyrightText", widget: "string"}
      - {
          label: "Sections",
          name: "title",
          widget: "list",
          field: {label: "Section", name: "section", widget: "relation", collection: "footer-section", search_fields: ["title"], value_field: "title", display_fields: ["title"]}
        }