backend:
  name: git-gateway
  repo: mbernardes19/o-portal-do-empreendedor.git
  branch: main
media_folder: public/images/uploads
local_backend:
  url: http://localhost:8081/api/v1
  allowed_hosts: ['127.0.0.1']
collections:
  - name: "footer-section"
    label: "Footer Section"
    folder: "content/footer-section"
    create: true
    slug: "{{footer-section-wrapper.title}}"
    format: json
    fields:
      - {
        label: "Footer Section Wrapper",
        name: "footer-section-wrapper",
        widget: "object",
        summary: "{{fields.title}}",
        fields: [
          {label: "Title", name: "title", widget: "string"},
          {
            label: "Links",
            name: "links",
            widget: "list",
            summary: "{{fields.footer-section-wrapper.links.*.name}}",
            allow_add: true,
            fields: [
                  {
                    label: Name,
                    name: name,
                    widget: string
                  },
                  {
                    label: URL,
                    name: url,
                    widget: string
                  }
                ]
        }
        ]
      }
  - name: "footer"
    label: "Footer"
    folder: "content/footer"
    slug: "footer"
    format: json
    delete: false
    fields:
      - {label: "Copyright text", name: "copyrightText", widget: "string"}
      - {
        label: "Section List",
        name: "sections",
        widget: "list",
        field: {
          label: "Section",
          name: "sections",
          widget: "relation",
          collection: "footer-section",
          search_fields: ["footer-section-wrapper.title"],
          value_field: "footer-section-wrapper",
          display_fields: ["footer-section-wrapper.title"]
        }
      }